//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesPerProduct
    {
        public int Cpp_cppId { get; set; }
        public int Cpp_ProductC_productcId { get; set; }
        public int Cpp_Products_productId { get; set; }
    
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual Products Products { get; set; }
    }
}
